name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        working-directory: ./scripts/builder
        run: npm ci
      - name: Build site
        working-directory: ./scripts/builder
        run: npm run build
        env:
          VITE_MINIFY_HTML: 1
          VITE_MINIFY_CSS: 1
      - name: Add CNAME to build dir
        run: echo christophergrass.com > build/CNAME
      - name: Publish site to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
          github_token: ${{ secrets.ACCESS_TOKEN }}
