name: Deps

on:
  schedule:
    - cron: '0 4 * * 1'
  workflow_dispatch:

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Update dependencies
        working-directory: ./scripts/builder
        run: |
          git config user.name 'sea-grass'
          git config user.email 'sea-grass@users.noreply.github.com'
          npx npm-check-updates -u
          npm i
          npm run format
          git add package.json package-lock.json
          git commit -m "Bump package versions"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
